'use client';

import React, { useState, useEffect } from 'react';
import { useHostel } from '@/context/HostelContext';
import HostelSelector from '@/components/layout/HostelSelector';
import api from '@/lib/api';
import { motion, AnimatePresence } from 'framer-motion';
import { jsPDF } from "jspdf";
import autoTable from 'jspdf-autotable';
import { 
  Loader2,
  Receipt,
  ChevronDown,
  Calendar,
  Download,
  FileText,
  Filter,
  Search,
  Table as TableIcon,
  CreditCard,
  User,
  Building2,
  Activity,
  ArrowRight
} from 'lucide-react';
import { cn } from '@/lib/utils';

const ReportsPage = () => {
  const { selectedHostel } = useHostel();
  const [reportType, setReportType] = useState('revenue');
  const [startDate, setStartDate] = useState(new Date(new Date().setDate(1)).toISOString().split('T')[0]);
  const [endDate, setEndDate] = useState(new Date().toISOString().split('T')[0]);
  const [paymentMode, setPaymentMode] = useState('all');
  const [reportData, setReportData] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      setUser(JSON.parse(storedUser));
    }
  }, []);

  const handleGenerateReport = async () => {
    setLoading(true);
    try {
      const res = await api.get('/owner/reports', {
        params: { 
          type: reportType, 
          hostel_id: selectedHostel, 
          startDate, 
          endDate, 
          paymentMode 
        }
      });
      setReportData(res.data);
    } catch (err) {
      console.error('Error generating report:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPdf = () => {
    const doc = new jsPDF();
    const pageWidth = (doc as any).internal.pageSize.width;
    const pageHeight = (doc as any).internal.pageSize.height;
    
    // Header Styling
    doc.setFillColor(30, 41, 59); // Dark Slate
    doc.rect(0, 0, pageWidth, 45, 'F');
    
    // Logo / Title
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.text('MY HOSTEL', 14, 22);
    
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text('PREMIUM SAAS PORTFOLIO AUDIT', 14, 28);

    // Report Type Badge
    const reportLabel = `${reportType.toUpperCase()} AUDIT`;
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.roundedRect(pageWidth - 65, 12, 50, 10, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(reportLabel, pageWidth - 40, 18.5, { align: 'center' });

    // Meta Info
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.text(`Generated by: ${user?.name || 'Captain'}`, 14, 38);
    doc.text(`Period: ${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()}`, pageWidth - 14, 38, { align: 'right' });

    // Summary Statistics
    const totalAmount = reportData.reduce((sum, row) => sum + parseFloat(row.amount || '0'), 0);
    
    doc.setFillColor(248, 250, 252); // Slate 50
    doc.roundedRect(14, 55, pageWidth - 28, 25, 3, 3, 'F');
    
    doc.setTextColor(100, 116, 139); // Slate 500
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL VOLUME', 25, 65);
    doc.text('TOTAL ENTRIES', pageWidth / 2, 65);
    doc.text('PORTFOLIO FOCUS', pageWidth - 25, 65, { align: 'right' });
    
    doc.setTextColor(30, 41, 59); // Slate 900
    doc.setFontSize(14);
    doc.text(`Rs. ${totalAmount.toLocaleString()}`, 25, 74);
    doc.text(`${reportData.length} Records`, pageWidth / 2, 74);
    doc.text(selectedHostel === 'all' ? 'Entire Portfolio' : 'Specific Unit', pageWidth - 25, 74, { align: 'right' });

    let head: string[][] = [];
    let body: any[][] = [];

    if (reportType === 'revenue') {
      head = [['DATE', 'NAME', 'HOSTEL NAME', 'ROOM NUM', 'AMOUNT', 'METHOD', 'REFERENCE ID']];
      body = reportData.map(row => [
        new Date(row.date).toLocaleDateString(),
        row.student_name?.toUpperCase() || '-',
        row.hostel_name?.toUpperCase() || '-',
        row.room_number || '-',
        `Rs. ${parseFloat(row.amount || '0').toLocaleString()}`,
        row.mode?.toUpperCase() || '-',
        row.transaction_id || row.receipt_id || '-'
      ]);
    } else {
      head = [['DATE', 'AUDIT DETAIL', 'HOSTEL NAME', 'AMOUNT', 'CATEGORY', 'AUTHORIZED BY']];
      body = reportData.map(row => [
        new Date(row.date).toLocaleDateString(),
        row.detail?.toUpperCase() || '-',
        row.hostel_name?.toUpperCase() || '-',
        `Rs. ${parseFloat(row.amount || '0').toLocaleString()}`,
        row.mode?.toUpperCase() || '-',
        row.received_by?.toUpperCase() || '-'
      ]);
    }

    autoTable(doc, {
      startY: 90,
      head: head,
      body: body,
      theme: 'striped',
      headStyles: { 
        fillColor: [30, 41, 59], 
        textColor: [255, 255, 255], 
        fontSize: 7,
        fontStyle: 'bold',
        cellPadding: 4,
        halign: 'left'
      },
      styles: { 
        fontSize: 7, 
        cellPadding: 4, 
        font: 'helvetica',
        textColor: [71, 85, 105],
        lineColor: [241, 245, 249],
        lineWidth: 0.1
      },
      columnStyles: {
        4: { fontStyle: 'bold', textColor: [30, 41, 59], halign: 'right' } // Amount column
      },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      margin: { left: 14, right: 14 },
      didDrawPage: (data) => {
        // Footer
        doc.setFontSize(7);
        doc.setTextColor(148, 163, 184);
        const str = `Page ${doc.getNumberOfPages()}`;
        doc.text(str, pageWidth - 20, pageHeight - 10);
        doc.text(`Audit generated on ${new Date().toLocaleString()}`, 14, pageHeight - 10);
      }
    });

    doc.save(`${reportType}_audit_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#FDFDFF]">
      {/* HEADER */}
      <header className="px-6 py-8 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-[#1E293B] tracking-tight">Reports & Analytics Engine</h1>
          <p className="text-[#64748B] text-[10px] font-bold uppercase tracking-[0.2em] mt-1">Audit Logs & Portfolio Data Exports</p>
        </div>
        <div className="flex items-center gap-4">
          <HostelSelector />
          <div className="w-10 h-10 rounded-full bg-[#EEF2FF] flex items-center justify-center text-[#4F46E5] font-black text-sm">
            {user?.name?.charAt(0) || 'C'}
          </div>
        </div>
      </header>

      <div className="px-6 pb-24 space-y-10">
        {/* CONFIGURATION CARD */}
        <motion.div 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white p-10 rounded-[3rem] border border-[#F1F5F9] shadow-sm"
        >
          <div className="flex items-center gap-3 mb-10">
            <Filter className="text-[#4F46E5]" size={20} />
            <h2 className="text-xs font-black text-[#1E293B] uppercase tracking-widest">Report Configuration</h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8">
            <div className="space-y-2">
              <label className="text-[8px] font-black text-[#94A3B8] uppercase tracking-widest ml-1">Report Focus</label>
              <div className="relative">
                <select 
                  value={reportType} 
                  onChange={(e) => setReportType(e.target.value)}
                  className="w-full bg-[#F8FAFC] border border-[#F1F5F9] rounded-2xl px-4 py-3 text-xs font-bold text-[#1E293B] outline-none focus:border-[#4F46E5] focus:bg-white transition-all appearance-none"
                >
                  <option value="revenue">Revenue Audit</option>
                  <option value="expenses">Expense Audit</option>
                </select>
                <ChevronDown size={14} className="absolute right-4 top-1/2 -translate-y-1/2 text-[#94A3B8] pointer-events-none" />
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-[8px] font-black text-[#94A3B8] uppercase tracking-widest ml-1">Start Period</label>
              <input 
                type="date" 
                value={startDate} 
                onChange={(e) => setStartDate(e.target.value)}
                className="w-full bg-[#F8FAFC] border border-[#F1F5F9] rounded-2xl px-4 py-3 text-xs font-bold text-[#1E293B] outline-none focus:border-[#4F46E5] focus:bg-white transition-all"
              />
            </div>

            <div className="space-y-2">
              <label className="text-[8px] font-black text-[#94A3B8] uppercase tracking-widest ml-1">End Period</label>
              <input 
                type="date" 
                value={endDate} 
                onChange={(e) => setEndDate(e.target.value)}
                className="w-full bg-[#F8FAFC] border border-[#F1F5F9] rounded-2xl px-4 py-3 text-xs font-bold text-[#1E293B] outline-none focus:border-[#4F46E5] focus:bg-white transition-all"
              />
            </div>

            <div className="space-y-2">
              <label className="text-[8px] font-black text-[#94A3B8] uppercase tracking-widest ml-1">Filter Mode</label>
              <div className="relative">
                <select 
                  value={paymentMode} 
                  onChange={(e) => setPaymentMode(e.target.value)}
                  className="w-full bg-[#F8FAFC] border border-[#F1F5F9] rounded-2xl px-4 py-3 text-xs font-bold text-[#1E293B] outline-none focus:border-[#4F46E5] focus:bg-white transition-all appearance-none"
                >
                  <option value="all">All Modes</option>
                  <option value="UPI">UPI</option>
                  <option value="Cash">Cash</option>
                  <option value="Bank Transfer">Bank Transfer</option>
                </select>
                <ChevronDown size={14} className="absolute right-4 top-1/2 -translate-y-1/2 text-[#94A3B8] pointer-events-none" />
              </div>
            </div>

            <div className="flex items-end gap-3">
              <button 
                onClick={handleGenerateReport}
                disabled={loading}
                className="flex-1 bg-[#4F46E5] hover:bg-[#4338CA] text-white rounded-2xl px-6 py-3 text-[10px] font-black uppercase tracking-widest shadow-lg shadow-indigo-100 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {loading ? <Loader2 size={14} className="animate-spin" /> : <Activity size={14} />}
                Generate
              </button>
              {reportData.length > 0 && (
                <button 
                  onClick={handleDownloadPdf}
                  className="bg-[#ECFDF5] hover:bg-[#D1FAE5] text-[#059669] rounded-2xl px-4 py-3 shadow-sm transition-all"
                >
                  <Download size={18} />
                </button>
              )}
            </div>
          </div>
        </motion.div>

        {/* PREVIEW AREA */}
        <AnimatePresence mode="wait">
          {reportData.length > 0 ? (
            <motion.div 
              key="table"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="bg-white rounded-[3rem] border border-[#F1F5F9] shadow-sm overflow-hidden"
            >
              <div className="p-8 border-b border-[#F1F5F9] flex items-center justify-between bg-[#F8FAFC]">
                <div className="flex items-center gap-3">
                  <TableIcon className="text-[#4F46E5]" size={18} />
                  <h2 className="text-xs font-black text-[#1E293B] uppercase tracking-widest">Previewing {reportData.length} Entries</h2>
                </div>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="bg-[#F8FAFC]">
                      <th className="px-8 py-4 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Date</th>
                      <th className="px-8 py-4 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">
                        {reportType === 'revenue' ? 'Name' : 'Audit Detail'}
                      </th>
                      <th className="px-8 py-4 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Hostel Name</th>
                      {reportType === 'revenue' && (
                        <th className="px-8 py-4 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Room Num</th>
                      )}
                      <th className="px-8 py-4 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Amount</th>
                      <th className="px-8 py-4 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Mode</th>
                      <th className="px-8 py-4 text-[8px] font-black text-[#94A3B8] uppercase tracking-widest">Reference</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#F1F5F9]">
                    {reportData.map((row, idx) => (
                      <tr key={idx} className="hover:bg-[#F8FAFC] transition-all group">
                        <td className="px-8 py-5 text-[10px] font-bold text-[#64748B]">
                          {new Date(row.date).toLocaleDateString()}
                        </td>
                        <td className="px-8 py-5">
                          <p className="text-[11px] font-black text-[#1E293B] group-hover:text-[#4F46E5] transition-all">
                            {reportType === 'revenue' ? (row.student_name || 'N/A') : (row.detail || 'N/A')}
                          </p>
                        </td>
                        <td className="px-8 py-5">
                          <div className="flex items-center gap-2">
                            <Building2 size={12} className="text-[#94A3B8]" />
                            <span className="text-[10px] font-bold text-[#475569]">{row.hostel_name || 'N/A'}</span>
                          </div>
                        </td>
                        {reportType === 'revenue' && (
                          <td className="px-8 py-5 text-[10px] font-bold text-[#475569]">
                            {row.room_number || 'N/A'}
                          </td>
                        )}
                        <td className="px-8 py-5">
                          <span className="text-[11px] font-black text-[#1E293B]">₹{parseFloat(row.amount || '0').toLocaleString()}</span>
                        </td>
                        <td className="px-8 py-5">
                          <span className={cn(
                            "px-2 py-1 rounded-lg text-[8px] font-black uppercase tracking-tighter",
                            row.mode === 'Cash' ? "bg-[#FFFBEB] text-[#D97706]" : "bg-[#EEF2FF] text-[#4F46E5]"
                          )}>
                            {row.mode}
                          </span>
                        </td>
                        <td className="px-8 py-5">
                          <p className="text-[8px] font-black text-[#94A3B8] uppercase tracking-widest leading-tight">
                            ID: {row.transaction_id?.substring(0, 10) || 'N/A'}<br/>
                            RCPT: {row.receipt_id || 'N/A'}
                          </p>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </motion.div>
          ) : (
            <motion.div 
              key="empty"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="bg-white p-24 rounded-[3rem] border border-dashed border-[#E2E8F0] flex flex-col items-center justify-center text-center"
            >
              <div className="w-20 h-20 bg-[#F8FAFC] rounded-full flex items-center justify-center mb-8 border border-[#F1F5F9]">
                <FileText size={32} className="text-[#CBD5E1]" />
              </div>
              <h3 className="text-lg font-black text-[#1E293B] tracking-tight">No data available</h3>
              <p className="text-[#94A3B8] text-[10px] font-bold uppercase tracking-[0.2em] mt-3 max-w-xs">
                Configure your audit parameters and click generate to see preview.
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default ReportsPage;